version: "3"
services:
    frontend:
        container_name: studiz-frontend
        build: .
        image: ghcr.io/studiz/studiz-frontend:dev
        restart: on-failure
        networks: frontend
    reverse-poxy:
        image: nginx
        container_name: reverse-poxy
        volumes: 
            - ./reverse-poxy.conf:/etc/nginx/nginx.conf
            - ../../certificateFiles:/etc/nginx/certificateFiles
        restart: on-failure
        ports:
            - "80:80"
            - "443:443"
        networks: frontend
networks:
    frontend:
        name: studiz-frontend-network
        external: true