version: "3"
services:
    frontend:
        container_name: studiz-frontend
        build: .
        image: ghcr.io/studiz/studiz-frontend:dev
        restart: on-failure
    reverse-poxy:
        image: nginx
        environment:
            API_HOST: http://20.239.140.141/:9091/api
        container_name: reverse-poxy
        volumes: 
            - ./reverse-poxy.conf:/etc/nginx/nginx.conf
        restart: on-failure
        ports:
            - "80:80"
  