version: "3"
services:
  reverse-poxy:
        image: nginx
        container_name: reverse-poxy
        volumes: 
            - ./nginx.conf:/etc/nginx/nginx.conf
        restart: on-failure
        ports:
            - "80:80"
  # frontend:
  #   container_name: frontend-dev
  #   build: .
  #   image: ghcr.io/studiz/studiz-frontend:dev