name: studiz-student-prd

on:
  pull_request:
    branches: [ main ]
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v3

      - name: Docker Login
      - uses: docker/login-action@v2.0.0
      - with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images 
      - uses: docker/build-push-action@v3.0.0
      - with:
          context: .
          push: true
          tags: ghcr.io/Studiz/studiz-student:prd
