name: studiz-frontend-dev

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Docker Login
      #   uses: docker/login-action@v2.0.0
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to a container registry
        uses: azure/docker-login@v1
        with:
          login-server: studiz.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
        run:
          docker build . -t studiz.azurecr.io/studiz-frontend:dev
          docker push studiz.azurecr.io/studiz-frontend:dev

      - name: Build and push Docker images 
        uses: docker/build-push-action@v3.0.0
        with:
          context: .
          push: true
          tags: ghcr.io/studiz/studiz-student:dev